Header angepasst
muhanad-musawi/beispiel-speisekarte pull request #10
Opened 2022-10-14 15:14 UTC by muhanad-musawi

2022-10-14 15:58 UTC, fabiandarga requested changes

2022-10-14 15:58 UTC, fabiandarga commented on src/App.scss
> +    position: relative;
da das ja nicht geklappt hat, wieder entfernen.

2022-10-14 15:58 UTC, fabiandarga commented on src/App.scss
> +    width: inherit;
da das ja nicht geklappt hat, wieder entfernen.

2022-10-14 15:58 UTC, fabiandarga commented on src/themes/chezhugo/main.scss
> +  background-image: none;
Das sollte besser mit einer variable überschrieben werden.
In der src/App.scss musst du die backgroundcolor mit einer variable austauschen.

2022-10-14 15:58 UTC, fabiandarga commented on src/themes/chezhugo/main.scss
> +  color: #606060;
Das sollte auch mit einer variable möglich sein

2022-10-14 15:58 UTC, fabiandarga commented on src/themes/chezhugo/main.scss
> +  background: url("../../images/chezHugo.png") no-repeat center / contain;
Das Bild sollte im selben Theme ordner sein:
`/themes/chezhuga/images/`

2022-10-14 15:58 UTC, fabiandarga commented on src/themes/chezhugo/main.scss
> +    background: url("../../images/chezHugo.png") no-repeat center / contain;
Die Zeile brauchst du nicht noch mal

2022-10-14 15:58 UTC, fabiandarga commented on src/themes/rancho/main.scss
> +      url("../../images/background3.jpg") no-repeat center 0px / 100% fixed;
Das Bild auch gerne in den rancho Ordner verschieben
`themes/rancho/images/`

2022-10-17 08:09 UTC, muhanad-musawi commented on src/themes/chezhugo/main.scss
> +  background-image: none;
ich habe das leider nicht so wirklich verstanden.

2022-10-17 08:24 UTC, merged